"""add column description to playlist item

Revision ID: 0901a7bd5b4b
Revises: 277003c2e331
Create Date: 2025-08-23 21:55:31.359485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0901a7bd5b4b'
down_revision: Union[str, Sequence[str], None] = '277003c2e331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlist_items', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('playlist_items', 'description')
    # ### end Alembic commands ###
