"""create playlists and items

Revision ID: 277003c2e331
Revises: a6562fd44fc9
Create Date: 2025-08-23 19:47:48.959526

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '277003c2e331'
down_revision: Union[str, Sequence[str], None] = 'a6562fd44fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('thumbnail', sa.String(), nullable=True))
    op.drop_column('channels', 'profileImage')
    op.add_column('playlist_items', sa.Column('key', sa.String(), nullable=True))
    op.add_column('playlist_items', sa.Column('thumbnail', sa.String(), nullable=False))
    op.create_index(op.f('ix_playlist_items_key'), 'playlist_items', ['key'], unique=True)
    op.add_column('playlists', sa.Column('thumbnail', sa.String(), nullable=True))
    op.drop_column('playlists', 'profileImage')
    op.drop_column('playlists', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('playlists', sa.Column('url', sa.VARCHAR(), nullable=True))
    op.add_column('playlists', sa.Column('profileImage', sa.VARCHAR(), nullable=True))
    op.drop_column('playlists', 'thumbnail')
    op.drop_index(op.f('ix_playlist_items_key'), table_name='playlist_items')
    op.drop_column('playlist_items', 'thumbnail')
    op.drop_column('playlist_items', 'key')
    op.add_column('channels', sa.Column('profileImage', sa.VARCHAR(), nullable=True))
    op.drop_column('channels', 'thumbnail')
    # ### end Alembic commands ###
