"""Added new field to User model

Revision ID: a6562fd44fc9
Revises: 
Create Date: 2025-08-05 04:17:51.894666

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6562fd44fc9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('title', sa.String(), nullable=True))
    op.drop_index(op.f('ix_channels_username'), table_name='channels')
    op.create_index(op.f('ix_channels_key'), 'channels', ['key'], unique=True)
    op.create_index(op.f('ix_channels_title'), 'channels', ['title'], unique=False)
    op.drop_column('channels', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('channels', sa.Column('username', sa.VARCHAR(), nullable=True))
    op.drop_index(op.f('ix_channels_title'), table_name='channels')
    op.drop_index(op.f('ix_channels_key'), table_name='channels')
    op.create_index(op.f('ix_channels_username'), 'channels', ['username'], unique=1)
    op.drop_column('channels', 'title')
    # ### end Alembic commands ###
